from seutil import CliUtils, LoggingUtils, IOUtils, BashUtils
import os
from ui.Environment import Environment
from ui.Macros import Macros
from ui.labels.keyword_fraggen import label_paths_xlsx_format, label_paths_json_format_offline

'''
Entry points of running code
'''
# python -m ui.main labeled_tests --project="addressbook" --crawlfolder="/Users/xyz/tackle-test-generator-ui-level/testlabeling/results/frag-gen-updated/addressbook"
def labeled_tests(**options):
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    project_name = options.get("project")
    crawl_folder_path = options.get("crawlfolder")
    if not project_name:
        print("please provide project name")
    if not crawl_folder_path:
        print("please provide absolute path of crawl folder generated by Crawljax")
    label_paths_xlsx_format(project_name, crawl_folder_path)
    label_paths_json_format_offline(project_name, crawl_folder_path)
    with IOUtils.cd(Macros.project_dir / "labelled_testcasegenerator-plugin"):
        BashUtils.run("mvn clean package -DskipTests")
        label_json_path = Macros.results_dir/"paths"/f"{project_name}-labels.json"
        BashUtils.run(f"mvn exec:java -Dexec.mainClass='com.crawljax.plugins.labelledTCG.OfflineTestGenerator' "
                      f"-Dexec.args='{crawl_folder_path} {label_json_path}'")